# Generated by Django 5.2.13 on 2026-05-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_rename_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, unique=True),
        ),
    ]
