# Generated by Django 5.2.13 on 2026-05-01 20:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0003_rename_columns'),
        ('wallets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding_source_added', models.BooleanField(default=False)),
                ('goals_created', models.BooleanField(default=False)),
                ('autosave_configured', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_progress_extended',
            },
        ),
        migrations.CreateModel(
            name='SavingPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed Amount', 'Fixed Amount')], max_length=20)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Every 2 Months', 'Every 2 Months')], max_length=20)),
                ('duration_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(4)])),
                ('routing_preference', models.CharField(choices=[('wallet', 'Savings Wallet'), ('invest', 'Direct to Investment')], default='wallet', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('next_deduction_at', models.DateTimeField()),
                ('commitment_end_at', models.DateTimeField()),
                ('funding_sources', models.ManyToManyField(related_name='saving_preferences', to='wallets.fundingsource')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saving_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saving_preferences',
            },
        ),
        migrations.CreateModel(
            name='DeductionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.fundingsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_logs', to=settings.AUTH_USER_MODEL)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_logs', to='autosave.savingpreference')),
            ],
            options={
                'db_table': 'deduction_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed Amount', 'Fixed Amount')], max_length=20)),
                ('weight_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goal_weights',
                'unique_together': {('user', 'goal')},
            },
        ),
    ]
