"use client";

import React, { createContext, useContext, useState, useEffect, useCallback } from "react";
import { API_ENDPOINTS, apiGet, apiPatch } from "./api";
import { formatTsh } from "./currency";

export type Currency = "TZS";
export type Language = "en-us" | "en-gb" | "fr" | "es" | "sw" | "ar";
export type Theme = "Light" | "Dark" | "System";

interface UserSettings {
  currency: Currency;
  language: Language;
  theme: Theme;
  dashboard_show_stats: boolean;
  dashboard_show_activity: boolean;
  dashboard_show_goals: boolean;
  analytics_enabled: boolean;
  personalized_tips_enabled: boolean;
  marketing_enabled: boolean;
}

interface SettingsContextType {
  settings: UserSettings;
  isLoading: boolean;
  updateSettings: (updates: Partial<UserSettings>) => Promise<void>;
  formatCurrency: (amount: number) => string;
  t: (key: string) => string;
}

const defaultSettings: UserSettings = {
  currency: "TZS",
  language: "en-us",
  theme: "System",
  dashboard_show_stats: true,
  dashboard_show_activity: true,
  dashboard_show_goals: true,
  analytics_enabled: true,
  personalized_tips_enabled: true,
  marketing_enabled: false,
};

const currencySymbols: Record<Currency, string> = {
  TZS: "TSh",
};

// Simple translations
const translations: Record<Language, Record<string, string>> = {
  "en-us": {
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.overview": "Here's your savings overview",
    "dashboard.balance": "Balance",
    "dashboard.savings": "Savings",
    "dashboard.investments": "Investments",
    "dashboard.goals": "Goals",
    "dashboard.transactions": "Transactions",
    "dashboard.quick_actions": "Quick Actions",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.view_all": "View All",
    "dashboard.total_portfolio": "Total Portfolio",
    "dashboard.this_month": "this month",
    "dashboard.savings_breakdown": "Savings Breakdown",
    "dashboard.performance": "Performance",
    "dashboard.available_balance": "Available Balance",
    "dashboard.active_goals": "Active Goals",
    "dashboard.invested_amount": "Invested Amount",
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.done": "Done",
    "common.close": "Close",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.amount": "Amount",
    "common.date": "Date",
    "common.status": "Status",
    "common.name": "Name",
    "common.description": "Description",
    "common.type": "Type",
    "common.category": "Category",
    "common.actions": "Actions",
    "common.setup": "Setup",
    "common.view": "View",
    "common.continue": "Continue",
    "common.submit": "Submit",
    "common.remove": "Remove",
    "common.update": "Update",
    "common.change": "Change",
    "common.add": "Add",
    "common.create": "Create",
    "common.select": "Select",
    // Profile
    "profile.title": "Profile",
    "profile.personal_info": "Personal Information",
    "profile.account": "Account",
    "profile.full_name": "Full Name",
    "profile.email": "Email Address",
    "profile.phone": "Phone Number",
    "profile.dob": "Date of Birth",
    "profile.location": "Location",
    "profile.bio": "Bio",
    "profile.member_since": "Member Since",
    "profile.member": "Member",
    "profile.total_saved": "Total Saved",
    "profile.goals_completed": "Goals Completed",
    "profile.active_goals": "Active Goals",
    "profile.profile_photo": "Profile Photo",
    "profile.upload_photo": "Upload photo",
    "profile.linked_accounts": "Linked Accounts",
    "profile.saving_preferences": "Saving Preferences",
    "profile.link_new_account": "Link New Account",
    "profile.no_linked_accounts": "No linked accounts",
    "profile.amount": "Amount",
    "profile.frequency": "Frequency",
    "profile.duration": "Duration",
    "profile.edit_preferences": "Edit Preferences",
    "profile.percentage": "Percentage",
    "profile.fixed_amount": "Fixed Amount",
    "profile.months": "months",
    "profile.per_cycle": "per cycle",
    // Goals
    "goals.title": "Goals",
    "goals.create_goal": "Create Goal",
    "goals.savings_goals": "Savings Goals",
    "goals.emergency_funds": "Emergency Funds",
    "goals.group_goals": "Group Goals",
    "goals.total_goals": "Total Goals",
    "goals.total_saved": "Total Saved",
    "goals.total_target": "Total Target",
    "goals.progress": "Progress",
    "goals.deadline": "Deadline",
    "goals.completed": "Completed",
    "goals.active": "Active",
    "goals.participants": "Participants",
    "goals.invite_code": "Invite Code",
    "goals.copy_link": "Copy Link",
    "goals.share": "Share",
    "goals.join": "Join",
    "goals.contribute": "Contribute",
    "goals.withdraw": "Withdraw",
    "goals.manage": "Manage",
    "goals.leave": "Leave Goal",
    "goals.no_goals": "No goals yet",
    "goals.track_manage": "Track and manage your savings goals",
    "goals.create_description": "Create a personal savings goal, an emergency fund, or a group goal that others can join and contribute to.",
    "goals.set_first_goal": "Set Your First Goal",
    "goals.target": "Target",
    "goals.current": "Current",
    "goals.create_savings": "Create Savings Goal",
    "goals.create_emergency": "Create Emergency Fund",
    "goals.create_group": "Create Group Goal",
    // Investments
    "investments.title": "Investments",
    "investments.available_funds": "Available Funds",
    "investments.my_investments": "My Investments",
    "investments.total_invested": "Total Invested",
    "investments.total_returns": "Total Returns",
    "investments.active_funds": "Active Funds",
    "investments.invest_now": "Invest Now",
    "investments.min_investment": "Min. Invest",
    "investments.annual_roi": "Annual ROI",
    "investments.duration": "Duration",
    "investments.risk_level": "Risk Level",
    "investments.low": "Low",
    "investments.medium": "Medium",
    "investments.high": "High",
    "investments.how_much": "How much to invest?",
    "investments.projected_return": "Projected 1-year return",
    "investments.review": "Review Investment",
    "investments.confirm": "Confirm Investment",
    "investments.funding_source": "Funding Source",
    "investments.reference": "Reference",
    "investments.investment_confirmed": "Investment Confirmed!",
    "investments.portfolio": "Portfolio",
    "investments.allocation": "Allocation",
    "investments.monthly_returns": "Monthly Returns",
    // Transactions
    "transactions.title": "Transactions",
    "transactions.history": "Your complete transaction history",
    "transactions.total_in": "Total In",
    "transactions.total_out": "Total Out",
    "transactions.net": "Net",
    "transactions.all": "All",
    "transactions.income": "Income",
    "transactions.expenses": "Expenses",
    "transactions.no_transactions": "No transactions found",
    "transactions.loading": "Loading transactions...",
    // Settings
    "settings.title": "Settings",
    "settings.notifications": "Notifications",
    "settings.security": "Security",
    "settings.preferences": "Preferences",
    "settings.privacy": "Privacy & Data",
    "settings.language": "Language",
    "settings.currency": "Currency",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.system": "System",
    "settings.password": "Password",
    "settings.change_password": "Change Password",
    "settings.current_password": "Current Password",
    "settings.new_password": "New Password",
    "settings.confirm_password": "Confirm New Password",
    "settings.2fa": "Two-Factor Authentication",
    "settings.sessions": "Active Sessions",
    "settings.login_history": "Login History",
    "settings.display_prefs": "Display Preferences",
    "settings.dashboard_layout": "Dashboard Layout",
    "settings.show_stats": "Show quick stats bar",
    "settings.show_activity": "Show recent activity feed",
    "settings.show_goals": "Show goal progress cards",
    "settings.privacy_data": "Your Data",
    "settings.export_data": "Export My Data",
    "settings.delete_account": "Delete Account",
    "settings.saved": "Saved!",
    // Funding Sources
    "funding.title": "Funding Sources",
    "funding.bank_account": "Bank Account",
    "funding.mobile_money": "Mobile Money",
    "funding.link_account": "Link Account",
    "funding.set_primary": "Set as Primary",
    "funding.remove": "Remove",
    // Wallet
    "wallet.title": "Wallet",
    "wallet.deposit": "Deposit",
    "wallet.withdraw": "Withdraw",
    "wallet.transfer": "Transfer",
  },
  "sw": {
    // Dashboard
    "dashboard.title": "Dashibodi",
    "dashboard.welcome": "Karibu tena",
    "dashboard.overview": "Hapa ni muhtasari wa akiba yako",
    "dashboard.balance": "Salio",
    "dashboard.savings": "Akiba",
    "dashboard.investments": "Uwekezaji",
    "dashboard.goals": "Malengo",
    "dashboard.transactions": "Miamala",
    "dashboard.quick_actions": "Vitendo vya Haraka",
    "dashboard.recent_activity": "Shughuli za Hivi Karibuni",
    "dashboard.view_all": "Tazama Zote",
    "dashboard.total_portfolio": "Jumla ya Mali",
    "dashboard.this_month": "mwezi huu",
    "dashboard.savings_breakdown": "Mgawanyo wa Akiba",
    "dashboard.performance": "Utendaji",
    "dashboard.available_balance": "Salio la Kupatikana",
    "dashboard.active_goals": "Malengo Aktifu",
    "dashboard.invested_amount": "Kiasi Kilichowekwa",
    // Common
    "common.save": "Hifadhi",
    "common.cancel": "Ghairi",
    "common.edit": "Hariri",
    "common.delete": "Futa",
    "common.loading": "Inapakia...",
    "common.error": "Kosa",
    "common.success": "Mafanikio",
    "common.confirm": "Thibitisha",
    "common.back": "Rudi",
    "common.next": "Inayofuata",
    "common.done": "Maliza",
    "common.close": "Funga",
    "common.search": "Tafuta",
    "common.filter": "Chuja",
    "common.sort": "Panga",
    "common.amount": "Kiasi",
    "common.date": "Tarehe",
    "common.status": "Hali",
    "common.name": "Jina",
    "common.description": "Maelezo",
    "common.type": "Aina",
    "common.category": "Kategoria",
    "common.actions": "Vitendo",
    "common.setup": "Sanidi",
    "common.view": "Tazama",
    "common.continue": "Endelea",
    "common.submit": "Wasiliana",
    "common.remove": "Ondoa",
    "common.update": "Sasisha",
    "common.change": "Badilisha",
    "common.add": "Ongeza",
    "common.create": "Unda",
    "common.select": "Chagua",
    // Profile
    "profile.title": "Wasifu",
    "profile.personal_info": "Taarifa za Kibinafsi",
    "profile.account": "Akaunti",
    "profile.full_name": "Jina Kamili",
    "profile.email": "Barua pepe",
    "profile.phone": "Nambari ya Simu",
    "profile.dob": "Tarehe ya Kuzaliwa",
    "profile.location": "Mahali",
    "profile.bio": "Maelezo Mafupi",
    "profile.member_since": "Mwanachama Tangu",
    "profile.member": "Mwanachama",
    "profile.total_saved": "Jumla Iliyohifadhiwa",
    "profile.goals_completed": "Malengo Yamekamilika",
    "profile.active_goals": "Malengo Aktifu",
    "profile.profile_photo": "Picha ya Wasifu",
    "profile.upload_photo": "Pakia picha",
    "profile.linked_accounts": "Akaunti Zilizounganishwa",
    "profile.saving_preferences": "Mapendeleo ya Akiba",
    "profile.link_new_account": "Unganisha Akaunti Mpya",
    "profile.no_linked_accounts": "Hakuna akaunti zilizounganishwa",
    "profile.amount": "Kiasi",
    "profile.frequency": "Muda",
    "profile.duration": "Muda wa Uwekaji",
    "profile.edit_preferences": "Hariri Mapendeleo",
    "profile.percentage": "Asilimia",
    "profile.fixed_amount": "Kiasi cha Kudumu",
    "profile.months": "miezi",
    "profile.per_cycle": "kwa mzunguko",
    // Goals
    "goals.title": "Malengo",
    "goals.create_goal": "Unda Lengo",
    "goals.savings_goals": "Malengo ya Akiba",
    "goals.emergency_funds": "Mfuko wa Dharura",
    "goals.group_goals": "Malengo ya Kikundi",
    "goals.total_goals": "Jumla ya Malengo",
    "goals.total_saved": "Jumla Iliyohifadhiwa",
    "goals.total_target": "Lengo la Jumla",
    "goals.progress": "Maendeleo",
    "goals.deadline": "Tarehe ya Mwisho",
    "goals.completed": "Imekamilika",
    "goals.active": "Inayoendelea",
    "goals.participants": "Wanachama",
    "goals.invite_code": "Msimbo wa Mwaliko",
    "goals.copy_link": "Nakili Kiunganishi",
    "goals.share": "Shirikisha",
    "goals.join": "Jiunge",
    "goals.contribute": "Changia",
    "goals.withdraw": "Toa",
    "goals.manage": "Simamia",
    "goals.leave": "Acha Lengo",
    "goals.no_goals": "Hakuna malengo bado",
    "goals.track_manage": "Fuatilia na simamia malengo yako ya akiba",
    "goals.create_description": "Unda lengo la kibinafsi la akiba, mfuko wa dharura, au lengo la kikundi ambapo wengine wanaweza kujiunga na kuchangia.",
    "goals.set_first_goal": "Weka Lengo Lako la Kwanza",
    "goals.target": "Lengo",
    "goals.current": "Sasa",
    "goals.create_savings": "Unda Lengo la Akiba",
    "goals.create_emergency": "Unda Mfuko wa Dharura",
    "goals.create_group": "Unda Lengo la Kikundi",
    // Investments
    "investments.title": "Uwekezaji",
    "investments.available_funds": "Mali Zinazopatikana",
    "investments.my_investments": "Uwekezaji Wangu",
    "investments.total_invested": "Jumla Iliyowekwa",
    "investments.total_returns": "Jumla ya Mapato",
    "investments.active_funds": "Mali Aktifu",
    "investments.invest_now": "Weka Pesa Sasa",
    "investments.min_investment": "Kiwango cha Chini",
    "investments.annual_roi": "Mapato ya Mwaka",
    "investments.duration": "Muda",
    "investments.risk_level": "Kiwango cha Hatari",
    "investments.low": "Chini",
    "investments.medium": "Wastani",
    "investments.high": "Juu",
    "investments.how_much": "Weka kiasi gani?",
    "investments.projected_return": "Mapato yanayotarajiwa baada ya mwaka",
    "investments.review": "Kagua Uwekezaji",
    "investments.confirm": "Thibitisha Uwekezaji",
    "investments.funding_source": "Chanzo cha Pesa",
    "investments.reference": "Marejeo",
    "investments.investment_confirmed": "Uwekezaji Umethibitishwa!",
    "investments.portfolio": "Mali",
    "investments.allocation": "Mgawanyo",
    "investments.monthly_returns": "Mapato ya Kila Mwezi",
    // Transactions
    "transactions.title": "Miamala",
    "transactions.history": "Historia yako yote ya miamala",
    "transactions.total_in": "Jumla Inayoingia",
    "transactions.total_out": "Jumla Inayotoka",
    "transactions.net": "Jumla ya Baki",
    "transactions.all": "Yote",
    "transactions.income": "Mapato",
    "transactions.expenses": "Matumizi",
    "transactions.no_transactions": "Hakuna miamala yaliyopatikana",
    "transactions.loading": "Inapakia miamala...",
    // Settings
    "settings.title": "Mipangilio",
    "settings.notifications": "Arifa",
    "settings.security": "Usalama",
    "settings.preferences": "Mapendeleo",
    "settings.privacy": "Faragha na Data",
    "settings.language": "Lugha",
    "settings.currency": "Sarafu",
    "settings.theme": "Mandhari",
    "settings.light": "Nuru",
    "settings.dark": "Giza",
    "settings.system": "Mfumo",
    "settings.password": "Nenosiri",
    "settings.change_password": "Badilisha Nenosiri",
    "settings.current_password": "Nenosiri la Sasa",
    "settings.new_password": "Nenosiri Mpya",
    "settings.confirm_password": "Thibitisha Nenosiri",
    "settings.2fa": "Uhalalishaji wa Hatua Mbili",
    "settings.sessions": "Vikao Vilivyoaktifu",
    "settings.login_history": "Historia ya Kuingia",
    "settings.display_prefs": "Mapendeleo ya Onyesho",
    "settings.dashboard_layout": "Mpangilio wa Dashibodi",
    "settings.show_stats": "Onyesha upau wa takwimu",
    "settings.show_activity": "Onyesha shughuli za hivi karibuni",
    "settings.show_goals": "Onyesha kadi za maendeleo ya malengo",
    "settings.privacy_data": "Data Yako",
    "settings.export_data": "Hamisha Data Yangu",
    "settings.delete_account": "Futa Akaunti",
    "settings.saved": "Imehifadhiwa!",
    // Funding Sources
    "funding.title": "Vyanzo vya Pesa",
    "funding.bank_account": "Akaunti ya Benki",
    "funding.mobile_money": "Pesa ya Simu",
    "funding.link_account": "Unganisha Akaunti",
    "funding.set_primary": "Weka kuu",
    "funding.remove": "Ondoa",
    // Wallet
    "wallet.title": "Mkoba",
    "wallet.deposit": "Weka Pesa",
    "wallet.withdraw": "Toa Pesa",
    "wallet.transfer": "Hamisha",
  },
  "en-gb": {
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome back",
    "dashboard.overview": "Here's your savings overview",
    "dashboard.balance": "Balance",
    "dashboard.savings": "Savings",
    "dashboard.investments": "Investments",
    "dashboard.goals": "Goals",
    "dashboard.transactions": "Transactions",
    "dashboard.quick_actions": "Quick Actions",
    "dashboard.recent_activity": "Recent Activity",
    "dashboard.view_all": "View All",
    "dashboard.total_portfolio": "Total Portfolio",
    "dashboard.this_month": "this month",
    "dashboard.savings_breakdown": "Savings Breakdown",
    "dashboard.performance": "Performance",
    "dashboard.available_balance": "Available Balance",
    "dashboard.active_goals": "Active Goals",
    "dashboard.invested_amount": "Invested Amount",
    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.next": "Next",
    "common.done": "Done",
    "common.close": "Close",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.amount": "Amount",
    "common.date": "Date",
    "common.status": "Status",
    "common.name": "Name",
    "common.description": "Description",
    "common.type": "Type",
    "common.category": "Category",
    "common.actions": "Actions",
    "common.setup": "Setup",
    "common.view": "View",
    "common.continue": "Continue",
    "common.submit": "Submit",
    "common.remove": "Remove",
    "common.update": "Update",
    "common.change": "Change",
    "common.add": "Add",
    "common.create": "Create",
    "common.select": "Select",
    // Profile
    "profile.title": "Profile",
    "profile.personal_info": "Personal Information",
    "profile.account": "Account",
    "profile.full_name": "Full Name",
    "profile.email": "Email Address",
    "profile.phone": "Phone Number",
    "profile.dob": "Date of Birth",
    "profile.location": "Location",
    "profile.bio": "Bio",
    "profile.member_since": "Member Since",
    "profile.member": "Member",
    "profile.total_saved": "Total Saved",
    "profile.goals_completed": "Goals Completed",
    "profile.active_goals": "Active Goals",
    "profile.profile_photo": "Profile Photo",
    "profile.upload_photo": "Upload photo",
    "profile.linked_accounts": "Linked Accounts",
    "profile.saving_preferences": "Saving Preferences",
    "profile.link_new_account": "Link New Account",
    "profile.no_linked_accounts": "No linked accounts",
    "profile.amount": "Amount",
    "profile.frequency": "Frequency",
    "profile.duration": "Duration",
    "profile.edit_preferences": "Edit Preferences",
    "profile.percentage": "Percentage",
    "profile.fixed_amount": "Fixed Amount",
    "profile.months": "months",
    "profile.per_cycle": "per cycle",
    // Goals
    "goals.title": "Goals",
    "goals.create_goal": "Create Goal",
    "goals.savings_goals": "Savings Goals",
    "goals.emergency_funds": "Emergency Funds",
    "goals.group_goals": "Group Goals",
    "goals.total_goals": "Total Goals",
    "goals.total_saved": "Total Saved",
    "goals.total_target": "Total Target",
    "goals.progress": "Progress",
    "goals.deadline": "Deadline",
    "goals.completed": "Completed",
    "goals.active": "Active",
    "goals.participants": "Participants",
    "goals.invite_code": "Invite Code",
    "goals.copy_link": "Copy Link",
    "goals.share": "Share",
    "goals.join": "Join",
    "goals.contribute": "Contribute",
    "goals.withdraw": "Withdraw",
    "goals.manage": "Manage",
    "goals.leave": "Leave Goal",
    "goals.no_goals": "No goals yet",
    "goals.track_manage": "Track and manage your savings goals",
    "goals.create_description": "Create a personal savings goal, an emergency fund, or a group goal that others can join and contribute to.",
    "goals.set_first_goal": "Set Your First Goal",
    "goals.target": "Target",
    "goals.current": "Current",
    "goals.create_savings": "Create Savings Goal",
    "goals.create_emergency": "Create Emergency Fund",
    "goals.create_group": "Create Group Goal",
    // Investments
    "investments.title": "Investments",
    "investments.available_funds": "Available Funds",
    "investments.my_investments": "My Investments",
    "investments.total_invested": "Total Invested",
    "investments.total_returns": "Total Returns",
    "investments.active_funds": "Active Funds",
    "investments.invest_now": "Invest Now",
    "investments.min_investment": "Min. Invest",
    "investments.annual_roi": "Annual ROI",
    "investments.duration": "Duration",
    "investments.risk_level": "Risk Level",
    "investments.low": "Low",
    "investments.medium": "Medium",
    "investments.high": "High",
    "investments.how_much": "How much to invest?",
    "investments.projected_return": "Projected 1-year return",
    "investments.review": "Review Investment",
    "investments.confirm": "Confirm Investment",
    "investments.funding_source": "Funding Source",
    "investments.reference": "Reference",
    "investments.investment_confirmed": "Investment Confirmed!",
    "investments.portfolio": "Portfolio",
    "investments.allocation": "Allocation",
    "investments.monthly_returns": "Monthly Returns",
    // Transactions
    "transactions.title": "Transactions",
    "transactions.history": "Your complete transaction history",
    "transactions.total_in": "Total In",
    "transactions.total_out": "Total Out",
    "transactions.net": "Net",
    "transactions.all": "All",
    "transactions.income": "Income",
    "transactions.expenses": "Expenses",
    "transactions.no_transactions": "No transactions found",
    "transactions.loading": "Loading transactions...",
    // Settings
    "settings.title": "Settings",
    "settings.notifications": "Notifications",
    "settings.security": "Security",
    "settings.preferences": "Preferences",
    "settings.privacy": "Privacy & Data",
    "settings.language": "Language",
    "settings.currency": "Currency",
    "settings.theme": "Theme",
    "settings.light": "Light",
    "settings.dark": "Dark",
    "settings.system": "System",
    "settings.password": "Password",
    "settings.change_password": "Change Password",
    "settings.current_password": "Current Password",
    "settings.new_password": "New Password",
    "settings.confirm_password": "Confirm New Password",
    "settings.2fa": "Two-Factor Authentication",
    "settings.sessions": "Active Sessions",
    "settings.login_history": "Login History",
    "settings.display_prefs": "Display Preferences",
    "settings.dashboard_layout": "Dashboard Layout",
    "settings.show_stats": "Show quick stats bar",
    "settings.show_activity": "Show recent activity feed",
    "settings.show_goals": "Show goal progress cards",
    "settings.privacy_data": "Your Data",
    "settings.export_data": "Export My Data",
    "settings.delete_account": "Delete Account",
    "settings.saved": "Saved!",
    // Funding Sources
    "funding.title": "Funding Sources",
    "funding.bank_account": "Bank Account",
    "funding.mobile_money": "Mobile Money",
    "funding.link_account": "Link Account",
    "funding.set_primary": "Set as Primary",
    "funding.remove": "Remove",
    // Wallet
    "wallet.title": "Wallet",
    "wallet.deposit": "Deposit",
    "wallet.withdraw": "Withdraw",
    "wallet.transfer": "Transfer",
  },
  "fr": {
    "dashboard.title": "Tableau de bord",
    "dashboard.welcome": "Bon retour",
    "dashboard.balance": "Solde",
    "dashboard.savings": "Épargne",
    "dashboard.investments": "Investissements",
    "dashboard.goals": "Objectifs",
    "dashboard.transactions": "Transactions",
    "dashboard.quick_actions": "Actions rapides",
    "dashboard.recent_activity": "Activité récente",
    "dashboard.view_all": "Voir tout",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.confirm": "Confirmer",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.done": "Terminé",
    "common.close": "Fermer",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    "common.amount": "Montant",
    "common.date": "Date",
    "common.status": "Statut",
    "common.name": "Nom",
    "common.description": "Description",
    "common.type": "Type",
    "common.category": "Catégorie",
    "common.actions": "Actions",
  },
  "es": {
    "dashboard.title": "Panel de control",
    "dashboard.welcome": "Bienvenido de nuevo",
    "dashboard.balance": "Saldo",
    "dashboard.savings": "Ahorros",
    "dashboard.investments": "Inversiones",
    "dashboard.goals": "Objetivos",
    "dashboard.transactions": "Transacciones",
    "dashboard.quick_actions": "Acciones rápidas",
    "dashboard.recent_activity": "Actividad reciente",
    "dashboard.view_all": "Ver todo",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.edit": "Editar",
    "common.delete": "Eliminar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "Éxito",
    "common.confirm": "Confirmar",
    "common.back": "Atrás",
    "common.next": "Siguiente",
    "common.done": "Hecho",
    "common.close": "Cerrar",
    "common.search": "Buscar",
    "common.filter": "Filtrar",
    "common.sort": "Ordenar",
    "common.amount": "Cantidad",
    "common.date": "Fecha",
    "common.status": "Estado",
    "common.name": "Nombre",
    "common.description": "Descripción",
    "common.type": "Tipo",
    "common.category": "Categoría",
    "common.actions": "Acciones",
  },
  "ar": {
    "dashboard.title": "لوحة التحكم",
    "dashboard.welcome": "مرحبًا بعودتك",
    "dashboard.balance": "الرصيد",
    "dashboard.savings": "المدخرات",
    "dashboard.investments": "الاستثمارات",
    "dashboard.goals": "الأهداف",
    "dashboard.transactions": "المعاملات",
    "dashboard.quick_actions": "إجراءات سريعة",
    "dashboard.recent_activity": "النشاط الأخير",
    "dashboard.view_all": "عرض الكل",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.edit": "تحرير",
    "common.delete": "حذف",
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجاح",
    "common.confirm": "تأكيد",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.done": "تم",
    "common.close": "إغلاق",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.sort": "فرز",
    "common.amount": "المبلغ",
    "common.date": "التاريخ",
    "common.status": "الحالة",
    "common.name": "الاسم",
    "common.description": "الوصف",
    "common.type": "النوع",
    "common.category": "الفئة",
    "common.actions": "الإجراءات",
  },
};

const SettingsContext = createContext<SettingsContextType | undefined>(undefined);

export function SettingsProvider({ children }: { children: React.ReactNode }) {
  const [settings, setSettings] = useState<UserSettings>(defaultSettings);
  const [isLoading, setIsLoading] = useState(true);

  // Load settings from backend
  useEffect(() => {
    const loadSettings = async () => {
      const token = localStorage.getItem("access_token");
      if (!token) {
        setIsLoading(false);
        return;
      }

      try {
        const data = await apiGet(API_ENDPOINTS.USER.SETTINGS);
        setSettings((prev) => ({
          ...prev,
          currency: "TZS",
          language: data.language || "en-us",
          theme: data.theme || "System",
          dashboard_show_stats: data.dashboard_show_stats ?? true,
          dashboard_show_activity: data.dashboard_show_activity ?? true,
          dashboard_show_goals: data.dashboard_show_goals ?? true,
          analytics_enabled: data.analytics_enabled ?? true,
          personalized_tips_enabled: data.personalized_tips_enabled ?? true,
          marketing_enabled: data.marketing_enabled ?? false,
        }));
      } catch (err) {
        console.error("Failed to load settings:", err);
      } finally {
        setIsLoading(false);
      }
    };

    loadSettings();
  }, []);

  // Apply theme
  useEffect(() => {
    const root = document.documentElement;
    if (settings.theme === "Dark") {
      root.classList.add("dark");
    } else if (settings.theme === "Light") {
      root.classList.remove("dark");
    } else {
      // System preference
      const prefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;
      if (prefersDark) {
        root.classList.add("dark");
      } else {
        root.classList.remove("dark");
      }
    }
  }, [settings.theme]);

  const updateSettings = useCallback(async (updates: Partial<UserSettings>) => {
    const token = localStorage.getItem("access_token");
    if (!token) return;

    try {
      const data = await apiPatch(API_ENDPOINTS.USER.SETTINGS, updates);
      setSettings((prev) => ({
        ...prev,
        ...updates,
        ...data,
      }));
    } catch (err) {
      console.error("Failed to update settings:", err);
      throw err;
    }
  }, []);

  const formatCurrency = useCallback(
    (amount: number) => {
      return formatTsh(amount);
    },
    []
  );

  const t = useCallback(
    (key: string) => {
      const lang = settings.language;
      return translations[lang]?.[key] || translations["en-us"][key] || key;
    },
    [settings.language]
  );

  return (
    <SettingsContext.Provider
      value={{ settings, isLoading, updateSettings, formatCurrency, t }}
    >
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  const context = useContext(SettingsContext);
  if (context === undefined) {
    throw new Error("useSettings must be used within a SettingsProvider");
  }
  return context;
}
