# Generated by Django 5.2.13 on 2026-05-02 14:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('provider_type', models.CharField(choices=[('bank', 'Bank'), ('mobile', 'Mobile Money')], max_length=10)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_providers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_saving_duration_months', models.IntegerField(default=4)),
                ('max_goals_per_user', models.IntegerField(default=10)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('maintenance_mode_enabled', models.BooleanField(default=False)),
                ('bank_linking_enabled', models.BooleanField(default=True)),
                ('mobile_money_enabled', models.BooleanField(default=True)),
                ('investments_enabled', models.BooleanField(default=True)),
                ('group_goals_enabled', models.BooleanField(default=True)),
                ('max_withdrawal_per_day', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=12)),
                ('max_investment_per_user', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=14)),
            ],
            options={
                'db_table': 'platform_settings',
            },
        ),
        migrations.CreateModel(
            name='MonthlyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('total_savings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('platform_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_transactions', models.IntegerField(default=0)),
                ('successful_transactions', models.IntegerField(default=0)),
                ('failed_transactions', models.IntegerField(default=0)),
                ('active_goals', models.IntegerField(default=0)),
                ('completed_goals', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'monthly_stats',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_dismiss_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical'), ('down', 'Down')], max_length=20)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('details', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'system_health',
                'ordering': ['service_name'],
                'unique_together': {('service_name',)},
            },
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('user_suspend', 'User Suspended'), ('user_activate', 'User Activated'), ('user_delete', 'User Deleted'), ('make_admin', 'Admin Granted'), ('revoke_admin', 'Admin Revoked'), ('withdrawal_approve', 'Withdrawal Approved'), ('withdrawal_reject', 'Withdrawal Rejected'), ('fund_create', 'Investment Fund Created'), ('fund_update', 'Investment Fund Updated'), ('fund_delete', 'Investment Fund Deleted'), ('settings_update', 'Settings Updated'), ('broadcast_send', 'Broadcast Sent'), ('alert_create', 'Alert Created'), ('alert_dismiss', 'Alert Dismissed')], max_length=50)),
                ('target_object_id', models.CharField(blank=True, max_length=50)),
                ('target_object_type', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'action'], name='admin_activ_admin_u_06e8a7_idx'), models.Index(fields=['target_user'], name='admin_activ_target__946f7d_idx'), models.Index(fields=['created_at'], name='admin_activ_created_625680_idx')],
            },
        ),
    ]
