# Generated by Django 5.2.13 on 2026-05-04 22:50

import common.utils
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentFund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Real Estate', 'Real Estate'), ('Agriculture', 'Agriculture'), ('Technology', 'Technology'), ('Energy', 'Energy')], max_length=20)),
                ('annual_roi', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'investment_funds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('projected_return', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('projected_value', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference_number', models.CharField(default=common.utils.generate_investment_ref, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('matured_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallets.fundingsource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.investmentfund')),
            ],
            options={
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('goals_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('emergency_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('investment_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('change_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_snapshots',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'created_at')},
            },
        ),
    ]
